---
- hosts: csr
  gather_facts: false
  connection: local
  tasks:
  - name: Show run
    ios_command:
      commands:
      - en
      - conf t
      - int g2
      - ip addr 10.42.42.42 255.255.255.0
      - desc This was set by Ansbile
      - no shut
      - do wr mem
      