---
- hosts: csr
  gather_facts: false
  connection: local
  tasks:
  - name: ssh login
    ios_system:
      username: cisco
      password: cisco
  - name: Show run
    ios_command:
      timeout: 45
      commands:
      - show run
    register: shrun
  - name: report information
    debug:
      var: shrun