---
- hosts: web
  tasks:
  - name: Create a folder in tmp directory
    file:
      dest: /tmp/ansible
      state: directory
  - name: Create a web-server file
    file:
      dest: /tmp/ansible/web-serverfile
      state: touch