---
- hosts: web
  tasks:
  - name: uninstall apache
    become: yes
    apt:
      name: apache2
      state: absent

- hosts: db
  tasks:
  - name: uninstall mariadb
    become: yes
    apt:
      name: mariadb-server
      state: absent