---
- hosts: linux
  tasks:
  - name: Create user (zwilliams/HomeworkDone!)
    user:
      name: zwilliams
      password: HomeworkDone!     #No password hash
    become: yes
  - name: Create second user (zwilliams2/User2)
    become: yes
    user:
      name: zwilliams2
      password: "{{ 'User2' | password_hash('sha512') }}"   #This will hash our password
  - name: Create third user (zwilliams3/User3)
    become: yes
    user:
      name: zwilliams3
      password: '$6$bTXcBI4qhW2tVao8$pAV0rJmiEFHqdmuc5XvgTq0YvYZljpx7p84jGDevtpAKlrnBcyeRVn9cqsE/BG/muAH1/7mAicLb//Rz2qDJT1'

- hosts: db
  tasks:
  - name: Running update as a seperate step
    apt:
      update_cache: yes
  - name: Install MariaDB
    become: yes
    apt:
      name: mariadb-server
      state: present
  - name: Enable mariaDB (set to auto-start)
    become: yes
    service:
      name: mariadb
      enabled: yes
  - name: Start mariadb
    become: yes
    service:
      name: mariadb
      state: started

- hosts: web
  tasks:
  - name: Install apache
    become: yes
    apt: name=apache2 state=present
  - name: Set apache to run
    become: yes
    service: name=apache2 state=started enabled=yes