---

- hosts: winserv
  gather_facts: false
  tasks:
  - name: create user
    win_user:
      name: Zachary
      password: Password01
  - name: install IIS
    win_feature:
      name: Web-Server
      state: present
  - name: install 7zip
    win_chocolatey:
      name: 7zip
      state: present
  - name: install Windows Updates
    win_updates:
      category_names: 
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups

      

